backend:
  image:
    repository: finmind-backend
    tag: tilt
  replicas: 1
  hpa:
    enabled: false
frontend:
  image:
    repository: finmind-frontend
    tag: tilt
  replicas: 1
  hpa:
    enabled: false
ingress:
  enabled: false
monitoring:
  enabled: false
