apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finmind.fullname" . }}-postgres
spec:
  replicas: {{ .Values.replicas.postgres }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "finmind.fullname" . }}-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "finmind.fullname" . }}-postgres-pvc
