apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finmind.frontend.serviceName" . }}
  namespace: {{ include "finmind.namespace" . }}
  labels:
    {{- include "finmind.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "finmind.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "finmind.frontend.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      {{- include "finmind.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: {{ .Values.frontend.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: {{ .Values.frontend.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
