{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "finmind.fullname" . }}-backend
  labels:
    {{- include "finmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "finmind.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
