apiVersion: v1
kind: Service
metadata:
  name: {{ include "finmind.redis.serviceName" . }}
  namespace: {{ include "finmind.namespace" . }}
  labels:
    {{- include "finmind.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "finmind.redis.selectorLabels" . | nindent 4 }}
