apiVersion: v1
kind: Service
metadata:
  name: {{ include "finmind.fullname" . }}-backend
  labels:
    {{- include "finmind.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "finmind.selectorLabels" . | nindent 4 }}
    component: backend
