{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "finmind.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finmind.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "finmind.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "finmind.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finmind.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "finmind.selectorLabels" . | nindent 6 }}
{{- end }}
