apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finmind-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - finmind.example.com
    secretName: finmind-tls
  rules:
  - host: finmind.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finmind-backend
            port:
              number: 80