k8s_yaml('k8s/deployment.yaml')
k8s_resource('finmind-web', port_forwards=5000)

docker_build('finmind-web', './app')

local_resource(
    'db',
    'docker run -d --name finmind-db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=finmind postgres:13',
    resource_deps=['finmind-web'],
    restart_on=['k8s/deployment.yaml'],
)

local_resource(
    'redis',
    'docker run -d --name finmind-redis redis:6',
    resource_deps=['finmind-web'],
    restart_on=['k8s/deployment.yaml'],
)

allow_k8s_contexts('minikube', 'docker-desktop')