build:
  docker:
    web: packages/backend/Dockerfile
  config:
    WORKDIR: packages/backend
run:
  web: sh -c 'python -m flask --app wsgi:app init-db && gunicorn --workers=2 --threads=4 --bind 0.0.0.0:$PORT wsgi:app'
release:
  command:
    - python -m flask --app wsgi:app init-db
addons:
  - plan: heroku-postgresql:essential-0
  - plan: heroku-redis:mini
